void sgemm4_ukernel(const float* A, const float* B, float* C) {
#ifdef __AVX2__
#ifdef __AVX512F__
#pragma message ("LIBXSMM KERNEL COMPILATION WARNING: compiling AVX2 code on AVX512 or newer architecture: " __FILE__)
#endif
  __asm__ __volatile__("movq %0, %%rsi\n\t"
                       "movq %1, %%rdi\n\t"
                       "movq %2, %%rdx\n\t"
                       "movq $0, %%r12\n\t"
                       "movq $0, %%r13\n\t"
                       "movq $0, %%r14\n\t"
                       "0:\n\t"
                       "addq $3, %%r13\n\t"
                       "movq $0, %%r12\n\t"
                       "1:\n\t"
                       "addq $4, %%r12\n\t"
                       "vmovups 0(%%rdx), %%xmm13\n\t"
                       "vmovups 16(%%rdx), %%xmm14\n\t"
                       "vmovups 32(%%rdx), %%xmm15\n\t"
                       "vmovups 0(%%rdi), %%xmm3\n\t"
                       "addq $16, %%rdi\n\t"
                       "vbroadcastss 0(%%rsi), %%xmm0\n\t"
                       "vfmadd231ps %%xmm3, %%xmm0, %%xmm13\n\t"
                       "vbroadcastss 16(%%rsi), %%xmm1\n\t"
                       "vfmadd231ps %%xmm3, %%xmm1, %%xmm14\n\t"
                       "vbroadcastss 32(%%rsi), %%xmm2\n\t"
                       "vfmadd231ps %%xmm3, %%xmm2, %%xmm15\n\t"
                       "vmovups 0(%%rdi), %%xmm3\n\t"
                       "addq $16, %%rdi\n\t"
                       "vbroadcastss 4(%%rsi), %%xmm0\n\t"
                       "vfmadd231ps %%xmm3, %%xmm0, %%xmm13\n\t"
                       "vbroadcastss 20(%%rsi), %%xmm1\n\t"
                       "vfmadd231ps %%xmm3, %%xmm1, %%xmm14\n\t"
                       "vbroadcastss 36(%%rsi), %%xmm2\n\t"
                       "vfmadd231ps %%xmm3, %%xmm2, %%xmm15\n\t"
                       "vmovups 0(%%rdi), %%xmm3\n\t"
                       "addq $16, %%rdi\n\t"
                       "vbroadcastss 8(%%rsi), %%xmm0\n\t"
                       "vfmadd231ps %%xmm3, %%xmm0, %%xmm13\n\t"
                       "vbroadcastss 24(%%rsi), %%xmm1\n\t"
                       "vfmadd231ps %%xmm3, %%xmm1, %%xmm14\n\t"
                       "vbroadcastss 40(%%rsi), %%xmm2\n\t"
                       "vfmadd231ps %%xmm3, %%xmm2, %%xmm15\n\t"
                       "vmovups 0(%%rdi), %%xmm3\n\t"
                       "addq $16, %%rdi\n\t"
                       "vbroadcastss 12(%%rsi), %%xmm0\n\t"
                       "vfmadd231ps %%xmm3, %%xmm0, %%xmm13\n\t"
                       "vbroadcastss 28(%%rsi), %%xmm1\n\t"
                       "vfmadd231ps %%xmm3, %%xmm1, %%xmm14\n\t"
                       "vbroadcastss 44(%%rsi), %%xmm2\n\t"
                       "vfmadd231ps %%xmm3, %%xmm2, %%xmm15\n\t"
                       "vmovups %%xmm13, 0(%%rdx)\n\t"
                       "vmovups %%xmm14, 16(%%rdx)\n\t"
                       "vmovups %%xmm15, 32(%%rdx)\n\t"
                       "addq $16, %%rdx\n\t"
                       "subq $48, %%rdi\n\t"
                       "cmpq $4, %%r12\n\t"
                       "jl 1b\n\t"
                       "addq $32, %%rdx\n\t"
                       "addq $48, %%rsi\n\t"
                       "subq $16, %%rdi\n\t"
                       "cmpq $3, %%r13\n\t"
                       "jl 0b\n\t"
                       "0:\n\t"
                       "addq $1, %%r13\n\t"
                       "movq $0, %%r12\n\t"
                       "1:\n\t"
                       "addq $4, %%r12\n\t"
                       "vmovups 0(%%rdx), %%xmm15\n\t"
                       "vmovups 0(%%rdi), %%xmm1\n\t"
                       "addq $16, %%rdi\n\t"
                       "vbroadcastss 0(%%rsi), %%xmm0\n\t"
                       "vfmadd231ps %%xmm1, %%xmm0, %%xmm15\n\t"
                       "vmovups 0(%%rdi), %%xmm1\n\t"
                       "addq $16, %%rdi\n\t"
                       "vbroadcastss 4(%%rsi), %%xmm0\n\t"
                       "vfmadd231ps %%xmm1, %%xmm0, %%xmm15\n\t"
                       "vmovups 0(%%rdi), %%xmm1\n\t"
                       "addq $16, %%rdi\n\t"
                       "vbroadcastss 8(%%rsi), %%xmm0\n\t"
                       "vfmadd231ps %%xmm1, %%xmm0, %%xmm15\n\t"
                       "vmovups 0(%%rdi), %%xmm1\n\t"
                       "addq $16, %%rdi\n\t"
                       "vbroadcastss 12(%%rsi), %%xmm0\n\t"
                       "vfmadd231ps %%xmm1, %%xmm0, %%xmm15\n\t"
                       "vmovups %%xmm15, 0(%%rdx)\n\t"
                       "addq $16, %%rdx\n\t"
                       "subq $48, %%rdi\n\t"
                       "cmpq $4, %%r12\n\t"
                       "jl 1b\n\t"
                       "addq $0, %%rdx\n\t"
                       "addq $16, %%rsi\n\t"
                       "subq $16, %%rdi\n\t"
                       "cmpq $4, %%r13\n\t"
                       "jl 0b\n\t"
                       : : "m"(B), "m"(A), "m"(C) : "rdi","rsi","rdx","r12","r13","r14","xmm0","xmm1","xmm2","xmm3","xmm4","xmm5","xmm6","xmm7","xmm8","xmm9","xmm10","xmm11","xmm12","xmm13","xmm14","xmm15");
#else
#pragma message ("LIBXSMM KERNEL COMPILATION ERROR in: " __FILE__)
#error No kernel was compiled, lacking support for current architecture?
#endif

#ifndef NDEBUG
#ifdef _OPENMP
#pragma omp atomic
#endif
libxsmm_num_total_flops += 128;
#endif
}

