void sgemm128_ukernel(const float* A, const float* B, float* C) {
#ifdef __AVX2__
#ifdef __AVX512F__
#pragma message ("LIBXSMM KERNEL COMPILATION WARNING: compiling AVX2 code on AVX512 or newer architecture: " __FILE__)
#endif
  __asm__ __volatile__("movq %0, %%rsi\n\t"
                       "movq %1, %%rdi\n\t"
                       "movq %2, %%rdx\n\t"
                       "movq $0, %%r12\n\t"
                       "movq $0, %%r13\n\t"
                       "movq $0, %%r14\n\t"
                       "0:\n\t"
                       "addq $3, %%r13\n\t"
                       "movq $0, %%r12\n\t"
                       "1:\n\t"
                       "addq $32, %%r12\n\t"
                       "vmovaps 0(%%rdx), %%ymm4\n\t"
                       "vmovaps 32(%%rdx), %%ymm5\n\t"
                       "vmovaps 64(%%rdx), %%ymm6\n\t"
                       "vmovaps 96(%%rdx), %%ymm7\n\t"
                       "vmovaps 512(%%rdx), %%ymm8\n\t"
                       "vmovaps 544(%%rdx), %%ymm9\n\t"
                       "vmovaps 576(%%rdx), %%ymm10\n\t"
                       "vmovaps 608(%%rdx), %%ymm11\n\t"
                       "vmovaps 1024(%%rdx), %%ymm12\n\t"
                       "vmovaps 1056(%%rdx), %%ymm13\n\t"
                       "vmovaps 1088(%%rdx), %%ymm14\n\t"
                       "vmovaps 1120(%%rdx), %%ymm15\n\t"
                       "movq $0, %%r14\n\t"
                       "2:\n\t"
                       "addq $4, %%r14\n\t"
                       "vbroadcastss 0(%%rsi), %%ymm0\n\t"
                       "vbroadcastss 512(%%rsi), %%ymm1\n\t"
                       "vbroadcastss 1024(%%rsi), %%ymm2\n\t"
                       "addq $4, %%rsi\n\t"
                       "vmovaps 0(%%rdi), %%ymm3\n\t"
                       "vfmadd231ps %%ymm3, %%ymm0, %%ymm4\n\t"
                       "vfmadd231ps %%ymm3, %%ymm1, %%ymm8\n\t"
                       "vfmadd231ps %%ymm3, %%ymm2, %%ymm12\n\t"
                       "vmovaps 32(%%rdi), %%ymm3\n\t"
                       "vfmadd231ps %%ymm3, %%ymm0, %%ymm5\n\t"
                       "vfmadd231ps %%ymm3, %%ymm1, %%ymm9\n\t"
                       "vfmadd231ps %%ymm3, %%ymm2, %%ymm13\n\t"
                       "vmovaps 64(%%rdi), %%ymm3\n\t"
                       "vfmadd231ps %%ymm3, %%ymm0, %%ymm6\n\t"
                       "vfmadd231ps %%ymm3, %%ymm1, %%ymm10\n\t"
                       "vfmadd231ps %%ymm3, %%ymm2, %%ymm14\n\t"
                       "vmovaps 96(%%rdi), %%ymm3\n\t"
                       "addq $512, %%rdi\n\t"
                       "vfmadd231ps %%ymm3, %%ymm0, %%ymm7\n\t"
                       "vfmadd231ps %%ymm3, %%ymm1, %%ymm11\n\t"
                       "vfmadd231ps %%ymm3, %%ymm2, %%ymm15\n\t"
                       "vbroadcastss 0(%%rsi), %%ymm0\n\t"
                       "vbroadcastss 512(%%rsi), %%ymm1\n\t"
                       "vbroadcastss 1024(%%rsi), %%ymm2\n\t"
                       "addq $4, %%rsi\n\t"
                       "vmovaps 0(%%rdi), %%ymm3\n\t"
                       "vfmadd231ps %%ymm3, %%ymm0, %%ymm4\n\t"
                       "vfmadd231ps %%ymm3, %%ymm1, %%ymm8\n\t"
                       "vfmadd231ps %%ymm3, %%ymm2, %%ymm12\n\t"
                       "vmovaps 32(%%rdi), %%ymm3\n\t"
                       "vfmadd231ps %%ymm3, %%ymm0, %%ymm5\n\t"
                       "vfmadd231ps %%ymm3, %%ymm1, %%ymm9\n\t"
                       "vfmadd231ps %%ymm3, %%ymm2, %%ymm13\n\t"
                       "vmovaps 64(%%rdi), %%ymm3\n\t"
                       "vfmadd231ps %%ymm3, %%ymm0, %%ymm6\n\t"
                       "vfmadd231ps %%ymm3, %%ymm1, %%ymm10\n\t"
                       "vfmadd231ps %%ymm3, %%ymm2, %%ymm14\n\t"
                       "vmovaps 96(%%rdi), %%ymm3\n\t"
                       "addq $512, %%rdi\n\t"
                       "vfmadd231ps %%ymm3, %%ymm0, %%ymm7\n\t"
                       "vfmadd231ps %%ymm3, %%ymm1, %%ymm11\n\t"
                       "vfmadd231ps %%ymm3, %%ymm2, %%ymm15\n\t"
                       "vbroadcastss 0(%%rsi), %%ymm0\n\t"
                       "vbroadcastss 512(%%rsi), %%ymm1\n\t"
                       "vbroadcastss 1024(%%rsi), %%ymm2\n\t"
                       "addq $4, %%rsi\n\t"
                       "vmovaps 0(%%rdi), %%ymm3\n\t"
                       "vfmadd231ps %%ymm3, %%ymm0, %%ymm4\n\t"
                       "vfmadd231ps %%ymm3, %%ymm1, %%ymm8\n\t"
                       "vfmadd231ps %%ymm3, %%ymm2, %%ymm12\n\t"
                       "vmovaps 32(%%rdi), %%ymm3\n\t"
                       "vfmadd231ps %%ymm3, %%ymm0, %%ymm5\n\t"
                       "vfmadd231ps %%ymm3, %%ymm1, %%ymm9\n\t"
                       "vfmadd231ps %%ymm3, %%ymm2, %%ymm13\n\t"
                       "vmovaps 64(%%rdi), %%ymm3\n\t"
                       "vfmadd231ps %%ymm3, %%ymm0, %%ymm6\n\t"
                       "vfmadd231ps %%ymm3, %%ymm1, %%ymm10\n\t"
                       "vfmadd231ps %%ymm3, %%ymm2, %%ymm14\n\t"
                       "vmovaps 96(%%rdi), %%ymm3\n\t"
                       "addq $512, %%rdi\n\t"
                       "vfmadd231ps %%ymm3, %%ymm0, %%ymm7\n\t"
                       "vfmadd231ps %%ymm3, %%ymm1, %%ymm11\n\t"
                       "vfmadd231ps %%ymm3, %%ymm2, %%ymm15\n\t"
                       "vbroadcastss 0(%%rsi), %%ymm0\n\t"
                       "vbroadcastss 512(%%rsi), %%ymm1\n\t"
                       "vbroadcastss 1024(%%rsi), %%ymm2\n\t"
                       "addq $4, %%rsi\n\t"
                       "vmovaps 0(%%rdi), %%ymm3\n\t"
                       "vfmadd231ps %%ymm3, %%ymm0, %%ymm4\n\t"
                       "vfmadd231ps %%ymm3, %%ymm1, %%ymm8\n\t"
                       "vfmadd231ps %%ymm3, %%ymm2, %%ymm12\n\t"
                       "vmovaps 32(%%rdi), %%ymm3\n\t"
                       "vfmadd231ps %%ymm3, %%ymm0, %%ymm5\n\t"
                       "vfmadd231ps %%ymm3, %%ymm1, %%ymm9\n\t"
                       "vfmadd231ps %%ymm3, %%ymm2, %%ymm13\n\t"
                       "vmovaps 64(%%rdi), %%ymm3\n\t"
                       "vfmadd231ps %%ymm3, %%ymm0, %%ymm6\n\t"
                       "vfmadd231ps %%ymm3, %%ymm1, %%ymm10\n\t"
                       "vfmadd231ps %%ymm3, %%ymm2, %%ymm14\n\t"
                       "vmovaps 96(%%rdi), %%ymm3\n\t"
                       "addq $512, %%rdi\n\t"
                       "vfmadd231ps %%ymm3, %%ymm0, %%ymm7\n\t"
                       "vfmadd231ps %%ymm3, %%ymm1, %%ymm11\n\t"
                       "vfmadd231ps %%ymm3, %%ymm2, %%ymm15\n\t"
                       "cmpq $128, %%r14\n\t"
                       "jl 2b\n\t"
                       "subq $512, %%rsi\n\t"
                       "vmovaps %%ymm4, 0(%%rdx)\n\t"
                       "vmovaps %%ymm5, 32(%%rdx)\n\t"
                       "vmovaps %%ymm6, 64(%%rdx)\n\t"
                       "vmovaps %%ymm7, 96(%%rdx)\n\t"
                       "vmovaps %%ymm8, 512(%%rdx)\n\t"
                       "vmovaps %%ymm9, 544(%%rdx)\n\t"
                       "vmovaps %%ymm10, 576(%%rdx)\n\t"
                       "vmovaps %%ymm11, 608(%%rdx)\n\t"
                       "vmovaps %%ymm12, 1024(%%rdx)\n\t"
                       "vmovaps %%ymm13, 1056(%%rdx)\n\t"
                       "vmovaps %%ymm14, 1088(%%rdx)\n\t"
                       "vmovaps %%ymm15, 1120(%%rdx)\n\t"
                       "addq $128, %%rdx\n\t"
                       "subq $65408, %%rdi\n\t"
                       "cmpq $128, %%r12\n\t"
                       "jl 1b\n\t"
                       "addq $1024, %%rdx\n\t"
                       "addq $1536, %%rsi\n\t"
                       "subq $512, %%rdi\n\t"
                       "cmpq $126, %%r13\n\t"
                       "jl 0b\n\t"
                       "0:\n\t"
                       "addq $2, %%r13\n\t"
                       "movq $0, %%r12\n\t"
                       "1:\n\t"
                       "addq $32, %%r12\n\t"
                       "vmovaps 0(%%rdx), %%ymm8\n\t"
                       "vmovaps 32(%%rdx), %%ymm9\n\t"
                       "vmovaps 64(%%rdx), %%ymm10\n\t"
                       "vmovaps 96(%%rdx), %%ymm11\n\t"
                       "vmovaps 512(%%rdx), %%ymm12\n\t"
                       "vmovaps 544(%%rdx), %%ymm13\n\t"
                       "vmovaps 576(%%rdx), %%ymm14\n\t"
                       "vmovaps 608(%%rdx), %%ymm15\n\t"
                       "movq $0, %%r14\n\t"
                       "2:\n\t"
                       "addq $4, %%r14\n\t"
                       "vbroadcastss 0(%%rsi), %%ymm0\n\t"
                       "vbroadcastss 512(%%rsi), %%ymm1\n\t"
                       "addq $4, %%rsi\n\t"
                       "vmovaps 0(%%rdi), %%ymm2\n\t"
                       "vfmadd231ps %%ymm2, %%ymm0, %%ymm8\n\t"
                       "vfmadd231ps %%ymm2, %%ymm1, %%ymm12\n\t"
                       "vmovaps 32(%%rdi), %%ymm2\n\t"
                       "vfmadd231ps %%ymm2, %%ymm0, %%ymm9\n\t"
                       "vfmadd231ps %%ymm2, %%ymm1, %%ymm13\n\t"
                       "vmovaps 64(%%rdi), %%ymm2\n\t"
                       "vfmadd231ps %%ymm2, %%ymm0, %%ymm10\n\t"
                       "vfmadd231ps %%ymm2, %%ymm1, %%ymm14\n\t"
                       "vmovaps 96(%%rdi), %%ymm2\n\t"
                       "addq $512, %%rdi\n\t"
                       "vfmadd231ps %%ymm2, %%ymm0, %%ymm11\n\t"
                       "vfmadd231ps %%ymm2, %%ymm1, %%ymm15\n\t"
                       "vbroadcastss 0(%%rsi), %%ymm0\n\t"
                       "vbroadcastss 512(%%rsi), %%ymm1\n\t"
                       "addq $4, %%rsi\n\t"
                       "vmovaps 0(%%rdi), %%ymm2\n\t"
                       "vfmadd231ps %%ymm2, %%ymm0, %%ymm8\n\t"
                       "vfmadd231ps %%ymm2, %%ymm1, %%ymm12\n\t"
                       "vmovaps 32(%%rdi), %%ymm2\n\t"
                       "vfmadd231ps %%ymm2, %%ymm0, %%ymm9\n\t"
                       "vfmadd231ps %%ymm2, %%ymm1, %%ymm13\n\t"
                       "vmovaps 64(%%rdi), %%ymm2\n\t"
                       "vfmadd231ps %%ymm2, %%ymm0, %%ymm10\n\t"
                       "vfmadd231ps %%ymm2, %%ymm1, %%ymm14\n\t"
                       "vmovaps 96(%%rdi), %%ymm2\n\t"
                       "addq $512, %%rdi\n\t"
                       "vfmadd231ps %%ymm2, %%ymm0, %%ymm11\n\t"
                       "vfmadd231ps %%ymm2, %%ymm1, %%ymm15\n\t"
                       "vbroadcastss 0(%%rsi), %%ymm0\n\t"
                       "vbroadcastss 512(%%rsi), %%ymm1\n\t"
                       "addq $4, %%rsi\n\t"
                       "vmovaps 0(%%rdi), %%ymm2\n\t"
                       "vfmadd231ps %%ymm2, %%ymm0, %%ymm8\n\t"
                       "vfmadd231ps %%ymm2, %%ymm1, %%ymm12\n\t"
                       "vmovaps 32(%%rdi), %%ymm2\n\t"
                       "vfmadd231ps %%ymm2, %%ymm0, %%ymm9\n\t"
                       "vfmadd231ps %%ymm2, %%ymm1, %%ymm13\n\t"
                       "vmovaps 64(%%rdi), %%ymm2\n\t"
                       "vfmadd231ps %%ymm2, %%ymm0, %%ymm10\n\t"
                       "vfmadd231ps %%ymm2, %%ymm1, %%ymm14\n\t"
                       "vmovaps 96(%%rdi), %%ymm2\n\t"
                       "addq $512, %%rdi\n\t"
                       "vfmadd231ps %%ymm2, %%ymm0, %%ymm11\n\t"
                       "vfmadd231ps %%ymm2, %%ymm1, %%ymm15\n\t"
                       "vbroadcastss 0(%%rsi), %%ymm0\n\t"
                       "vbroadcastss 512(%%rsi), %%ymm1\n\t"
                       "addq $4, %%rsi\n\t"
                       "vmovaps 0(%%rdi), %%ymm2\n\t"
                       "vfmadd231ps %%ymm2, %%ymm0, %%ymm8\n\t"
                       "vfmadd231ps %%ymm2, %%ymm1, %%ymm12\n\t"
                       "vmovaps 32(%%rdi), %%ymm2\n\t"
                       "vfmadd231ps %%ymm2, %%ymm0, %%ymm9\n\t"
                       "vfmadd231ps %%ymm2, %%ymm1, %%ymm13\n\t"
                       "vmovaps 64(%%rdi), %%ymm2\n\t"
                       "vfmadd231ps %%ymm2, %%ymm0, %%ymm10\n\t"
                       "vfmadd231ps %%ymm2, %%ymm1, %%ymm14\n\t"
                       "vmovaps 96(%%rdi), %%ymm2\n\t"
                       "addq $512, %%rdi\n\t"
                       "vfmadd231ps %%ymm2, %%ymm0, %%ymm11\n\t"
                       "vfmadd231ps %%ymm2, %%ymm1, %%ymm15\n\t"
                       "cmpq $128, %%r14\n\t"
                       "jl 2b\n\t"
                       "subq $512, %%rsi\n\t"
                       "vmovaps %%ymm8, 0(%%rdx)\n\t"
                       "vmovaps %%ymm9, 32(%%rdx)\n\t"
                       "vmovaps %%ymm10, 64(%%rdx)\n\t"
                       "vmovaps %%ymm11, 96(%%rdx)\n\t"
                       "vmovaps %%ymm12, 512(%%rdx)\n\t"
                       "vmovaps %%ymm13, 544(%%rdx)\n\t"
                       "vmovaps %%ymm14, 576(%%rdx)\n\t"
                       "vmovaps %%ymm15, 608(%%rdx)\n\t"
                       "addq $128, %%rdx\n\t"
                       "subq $65408, %%rdi\n\t"
                       "cmpq $128, %%r12\n\t"
                       "jl 1b\n\t"
                       "addq $512, %%rdx\n\t"
                       "addq $1024, %%rsi\n\t"
                       "subq $512, %%rdi\n\t"
                       "cmpq $128, %%r13\n\t"
                       "jl 0b\n\t"
                       : : "m"(B), "m"(A), "m"(C) : "rdi","rsi","rdx","r12","r13","r14","xmm0","xmm1","xmm2","xmm3","xmm4","xmm5","xmm6","xmm7","xmm8","xmm9","xmm10","xmm11","xmm12","xmm13","xmm14","xmm15");
#else
#pragma message ("LIBXSMM KERNEL COMPILATION ERROR in: " __FILE__)
#error No kernel was compiled, lacking support for current architecture?
#endif

#ifndef NDEBUG
#ifdef _OPENMP
#pragma omp atomic
#endif
  //libxsmm_num_total_flops += 4194304;
#endif
}

